---
version: "3"

services:
  app:
    depends_on:
      - db
    links:
      - db
    build:
      dockerfile: devops/Dockerfile
      context: ../
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://myuser:mypassword@db/mydatabase

  db:
    image: postgres:latest
    ports:
      - "6379:6379"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
